name: WavePortal

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - uses: "shivammathur/setup-php@v2"
      with:
        php-version: "8.1"
    - name: Install composer dependencies
      run: |
        composer install  
    - name: Create local changes
      run: |
        npm install && npm run build
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -A
        git commit -a -m "Add changes" || echo "No changes to commit"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
  deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ssh.waveportal.io
          username: u23-y8h46ibn9jbd
          key: ${{ secrets.KEY }}
          port: 18765
          script: |
             cd ~/www/dev.waveportal.io/public_html
             git pull origin main
             composer install
             php artisan migrate
             # php artisan db:seed --class=LocaleSeeder
